name: top_stock_manager
description: Stock Management system for a small shop that runs locally.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0

  # collection for indexed map
  collection: ^1.17.2

  drift: ^2.0.2+1
  sqlite3_flutter_libs: ^0.5.9
  path_provider: ^2.0.11

  # for combine multiple database queries
  rxdart: ^0.27.7

  path: ^1.8.1

  get: ^4.6.5
  get_storage: ^2.0.3

  uuid: ^3.0.6




  # icons
  cupertino_icons: ^1.0.6
  fluttericon: ^2.0.0

  # windows format of menus and submenus
  menu_bar: ^0.5.3
  window_manager: ^0.2.9


dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.0.2
  build_runner: ^2.2.0

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
